openapi: 3.0.1
info:
  title: Account Summary
  description: 'This service domain orchestrates a deposit account. The typical range of services and fees covers payments from and scheduled and ad-hoc loans to the account.'
  version: 11.0.0
servers:
  - url: https://virtserver.swaggerhub.com/BIAN-3/BIAN/SavingsAccount/11.0.0
paths:
  '/AccountSummary/{accountHolderId}/DepositAccounts/Retrieve':
    get:
      tags:
        - Account Summary
      summary: Retrieve Deposit Accounts
      description: Retrieve Deposit Accounts
      operationId: RetrieveAccounts
      parameters:
        - $ref: '#/components/parameters/accountHolderId'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveLoanAccountResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    AccountFacilityResponse:
      type: array
      items:
          type: object
          properties:
            productInstanceReference:
              type: string
              description: "\n"
              format: string
            accountNumber:
              type: string
              description: "\n"
              format: string
            customerReference:
              type: string
              description: "\n"
              format: string
            bankBranchLocationReference:
              type: string
              description: "\n"
              format: string
            accountType:
              type: string
              description: "\n"
              format: string
            accountStatus:
              type: string
              description: "\n"
              format: string
            accountCurrency:
              type: string
              description: "\n"
              format: string
            accountBalance:
              type: string
              description: "\n"
              format: string
            accountOriginationDate:
              type: string
              description: "\n"
              format: string
            lastModifiedDate:
              type: string
              description: "\n"
              format: string
            taxReference:
              type: string
              description: "\n"
              format: string
            entitlementOptionDefinition:
              type: string
              description: "\n"
              format: string
            entitlementOptionSetting:
              type: string
              description: "\n"
              format: string
            restrictionOptionDefinition:
              type: string
              description: "\n"
              format: string
            restrictionOptionSetting:
              type: string
              description: "\n"
              format: string
            associations:
              type: string
              description: "\n"
              format: string
            associationType:
              type: string
              description: "\n"
              format: string
            associationReference:
              type: string
              description: "\n"
              format: string
            customerCommentary:
              type: string
              description: "\n"
              format: string
            partyLegalStructureType:
              type: string
              description: "\n"
              format: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: "\n"
          format: string
        status:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
    RetrieveLoanAccountResponse:
        type: object
        properties:
            accountFacility:
              $ref: '#/components/schemas/AccountFacilityResponse'
  parameters:
    accountHolderId:
      name: accountHolderId
      in: path
      required: true
      schema:
        type: string
  responses:
    RetrieveLoanAccountResponse:
      description: InitiateLoanAccountResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveLoanAccountResponse'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
