openapi: 3.0.1
info:
  title: Customers
  description: Solar customers overview
  version: 1.0.1
servers:
- url: 'https://solar.com'
paths:
  '/Customers/Onboarding/Initiate':
    post:
      tags:
        - Customers
      summary: InBQ Initialize customer account.
      description: InBQ Initialize customer account.
      operationId: InitiateOnboarding
      requestBody:
        $ref: '#/components/requestBodies/InitiateOnboardingRequest'
      responses:
        '200':
          $ref: '#/components/responses/InitiateOnboardingResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/Customers/AdminOverView/Retrieve':
    get:
      tags:
        - Customers
      summary:  Retrieve the Admin overview
      description: Retrieve the Admin overview
      operationId: RetrieveOverView
      responses:
        '200':
          $ref: '#/components/responses/RetrieveAdminOverView'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    RetrieveAdminOverView:
      type: object
      properties:
        noofPlants:
          type: string
          description: "\n"
          format: string
        yieldToday:
          type: string
          description: "\n"
          format: string
        currentPower:
          type: string
          description: "\n"
          format: string
        totalYield:
          type: string
          description: "\n"
          format: string
        alerts:
          type: string
          description: "\n"
          format: string
        standardCoalSaved:
          type: string
          description: "\n"
          format: string
        co2Avoided:
          type: string
          description: "\n"
          format: string
        equivalentTreesPlanted:
          type: string
          description: "\n"
          format: string
    InitiateOnboardingRequest:
      type: object
      properties:
        plantName:
          type: string
          description: "\n"
          format: string
        emailId:
          type: string
          description: "\n"
          format: string
        location:
          type: string
          description: "\n"
          format: string
        uploadImages:
          type: string
          description: "\n"
          format: string
        uploadVideos:
          type: string
          description: "\n"
          format: string
        customerName:
          type: string
          description: "\n"
          format: string
        deviceName:
          type: string
          description: "\n"
          format: string
        deviceModel:
          type: string
          description: "\n"
          format: string
        deviceS/N:
          type: string
          description: "\n"
          format: string
        nominalPower:
          type: string
          description: "\n"
          format: string
    InitiateOnboardingResponse:
      type: object
      properties:
        deviceId:
          type: string
          description: "\n"
          format: string
        customerId:
          type: string
          description: "\n"
          format: string
        plantId:
          type: string
          description: "\n"
          format: string
        plantName:
          type: string
          description: "\n"
          format: string
        emailId:
          type: string
          description: "\n"
          format: string
        location:
          type: string
          description: "\n"
          format: string
        uploadImages:
          type: string
          description: "\n"
          format: string
        uploadVideos:
          type: string
          description: "\n"
          format: string
        customerName:
          type: string
          description: "\n"
          format: string
        deviceName:
          type: string
          description: "\n"
          format: string
        deviceModel:
          type: string
          description: "\n"
          format: string
        deviceS/N:
          type: string
          description: "\n"
          format: string
        nominalPower:
          type: string
          description: "\n"
          format: string
    HTTPError:
      type: object
      properties:
        statusCode:
          type: string
          description: "\n"
          format: string
        status:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
  parameters:
    plantId:
      name: plantId
      in: path
      required: true
      schema:
        type: string
    deviceId:
      name: deviceId
      in: path
      required: true
      schema:
        type: string
  requestBodies:
    InitiateOnboardingRequest:
        description: InitiateOnboardingRequest
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/InitiateOnboardingRequest'
  responses:
    RetrieveAdminOverView:
        description: RetrieveAdminOverView
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/RetrieveAdminOverView'
    InitiateOnboardingResponse:
        description: InitiateOnboardingResponse
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/InitiateOnboardingResponse'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
