openapi: 3.0.1
info:
  title: BIAN-TM-CurrentAccount-Service
  description: Handles all operations related to current accounts, including account creation, status updates. This service maps BIAN’s “Current Account” service domain to relevant Thought Machine core banking endpoints for seamless account lifecycle management.
  version: 11.0.0
servers:
- url: 'https://core-api.partner-integrations-sandbox.thirsty-fish-dephub.tmachine.io'
paths:
   /currentAccount/initiate:
    post:
      tags:
          - Accounts
      summary: InCR Initiate a current account for a customer
      description: InCR Initiate a current account for a customer
      operationId: InitiateCurrentAccount
      requestBody:
        $ref: '#/components/requestBodies/InitiateCurrentAccountRequest'
      responses:
        '200':
          $ref: '#/components/responses/InitiateCurrentAccountResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    productInstanceReference:
      type: object
      properties:
        currentAccountAgreement:
          type: string
          description: "\n"
          format: string
    StatusReason:
      type: object
      properties:
        Text:
          type: string
          description: "\n"
          format: string
    accountStatus:
      type: object
      properties:
        statusReason:
          $ref: '#/components/schemas/StatusReason'
    accountCurrency:
      type: object
      properties:
        currencyCode:
          type: string
          description: "\n"
          format: string
    accountDetails:
      type: object
      properties:
        customerReference:
          type: string
          description: "\n"
          format: string
        accountReference:
          type: string
          description: "\n"
          format: string
        accountCurrency:
          type: string
          description: "\n"
          format: string
        productInstanceReference:
          type: string
          description: "\n"
          format: string
        accountOpenDate:
          type: string
          description: "\n"
          format: string
        accountStatus:
          type: string
          description: "\n"
          format: string
    productInstanceParameters:
      type: object
      properties:
        inactivity_fee_application_day:
          type: string
          description: "\n"
          format: string
        maintenance_fee_application_day:
          type: string
          description: "\n"
          format: string
        minimum_balance_fee_application_day:
          type: string
          description: "\n"
          format: string
        roundup_autosave_active:
          type: string
          description: "\n"
          format: string
        unarranged_overdraft_fee_application_day:
          type: string
          description: "\n"
          format: string
        interest_application_day:
          type: string
          description: "\n"
          format: string
    currentAccountFacility:
      type: object
      properties:
        customerReference:
          type: string
          description: "\n"
          format: string
        productInstanceReference:
          $ref: '#/components/schemas/productInstanceReference'
        accountCurrency:
          $ref: '#/components/schemas/accountCurrency'
        accountStatus:
          $ref: '#/components/schemas/accountStatus'
        accountOpenDate:
          type: string
          description: "\n"
          format: string
        productInstanceParameters:
          $ref: '#/components/schemas/productInstanceParameters'
    InitiateCurrentAccountRequest:
      type: object
      properties:
        currentAccountFacility: 
          $ref: '#/components/schemas/currentAccountFacility'
    InitiateCurrentAccountResponse:
      type: object
      properties:
        accountDetails: 
          $ref: '#/components/schemas/accountDetails'
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: "\n"
          format: string
        status:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
  requestBodies:
    InitiateCurrentAccountRequest:
        description: createCurrentAccount
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/InitiateCurrentAccountRequest'
  responses:
    InitiateCurrentAccountResponse:
        description: createCurrentAccount
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/InitiateCurrentAccountResponse'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
