openapi: 3.0.1
info:
  title: Party-Mambu
  description: This API provides endpoints for managing customer information, including creating, retrieving, updating customer records.
  version: 11.0.1
servers:
- url: 'https://partnerfincuro.sandbox.mambu.com/api'
paths:
   /clients:
    post:
      tags:
          - Clients
      summary: InCR Initiate A new client
      description: InCR Initiate A client
      operationId: Initiate
      requestBody:
        $ref: '#/components/requestBodies/InitiateClientRequest'
      responses:
        '200':
          $ref: '#/components/responses/InitiateClientResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ExampleSelectFieldOption:
      type: object
      properties:
        example_option_id:
          type: string
          description: "\n"
          format: string
        example_option_value:
          type: string
          description: "\n"
          format: string
    ExampleGroupedCFSet:
      type: object
      properties:
        Example_Checkbox_Field:
          type: string
          description: "\n"
          format: string
        Example_Free_Text_Field:
          type: string
          description: "\n"
          format: string
        Example_Number_Field:
          type: string
          description: "\n"
          format: string
        Example_Select_Field:
          type: array
          items:
            $ref: '#/components/schemas/ExampleSelectFieldOption'
        _index:
          type: string
          description: "\n"
          format: string
    Address:
      type: object
      properties:
        city:
          type: string
          description: "\n"
          format: string
        country:
          type: string
          description: "\n"
          format: string
        indexInList:
          type: string
          description: "\n"
          format: string
        latitude:
          type: string
          description: "\n"
          format: string
        line1:
          type: string
          description: "\n"
          format: string
        line2:
          type: string
          description: "\n"
          format: string
        longitude:
          type: string
          description: "\n"
          format: string
        postcode:
          type: string
          description: "\n"
          format: string
        region:
          type: string
          description: "\n"
          format: string
    Attachments:
      type: object
      properties:
        fileName:
          type: string
          description: "\n"
          format: string
        fileSize:
          type: string
          description: "\n"
          format: string
        id:
          type: string
          description: "\n"
          format: string
        location:
          type: string
          description: "\n"
          format: string
        name:
          type: string
          description: "\n"
          format: string
        notes:
          type: string
          description: "\n"
          format: string
        type:
          type: string
          description: "\n"
          format: string
    IdDocument:
      type: object
      properties:
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachments'
        documentId:
          type: string
          description: "\n"
          format: string
        documentType:
          type: string
          description: "\n"
          format: string
        identificationDocumentTemplateKey:
          type: string
          description: "\n"
          format: string
        indexInList:
          type: string
          description: "\n"
          format: string
        issuingAuthority:
          type: string
          description: "\n"
          format: string
        validUntil:
          type: string
          description: "\n"
          format: string
    PortalSettings:
      type: object
      properties:
        lastLoggedInDate:
          type: string
          description: "\n"
          format: string
        portalState:
          type: string
          description: "\n"
          format: string
    ClientRequest:
      type: object
      properties:
        _Example_Custom_Fields:
          type: object
          properties:
            Example_Checkbox_Field:
              type: string
              description: "\n"
              format: string
            Example_ClientLink_Field:
              type: string
              description: "\n"
              format: string
            Example_Date_Field:
              type: string
              description: "\n"
              format: string
            Example_Datetime_Field:
              type: string
              description: "\n"
              format: string
            Example_Free_Text_Field:
              type: string
              description: "\n"
              format: string
            Example_GroupLink_Field:
              type: string
              description: "\n"
              format: string
            Example_Number_Field:
              type: string
              description: "\n"
              format: string
            Example_Select_Field:
                $ref: '#/components/schemas/ExampleSelectFieldOption'
            Example_UserLink_Field:
              type: string
              description: "\n"
              format: string
        _Example_Grouped_CF_Set:
          type: array
          items:
            $ref: '#/components/schemas/ExampleGroupedCFSet'
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
        assignedBranchKey:
          type: string
          description: "\n"
          format: string
        assignedCentreKey:
          type: string
          description: "\n"
          format: string
        assignedUserKey:
          type: string
          description: "\n"
          format: string
        birthDate:
          type: string
          description: "\n"
          format: string
        clientRoleKey:
          type: string
          description: "\n"
          format: string
        emailAddress:
          type: string
          description: "\n"
          format: string
        firstName:
          type: string
          description: "\n"
          format: string
        gender:
          type: string
          description: "\n"
          format: string
        groupKeys:
          type: array
          items:
            type: string
        homePhone:
          type: string
          description: "\n"
          format: string
        id:
          type: string
          description: "\n"
          format: string
        idDocuments:
          type: array
          items:
            $ref: '#/components/schemas/IdDocument'
        lastName:
          type: string
          description: "\n"
          format: string
        middleName:
          type: string
          description: "\n"
          format: string
        mobilePhone:
          type: string
          description: "\n"
          format: string
        mobilePhone2:
          type: string
          description: "\n"
          format: string
        notes:
          type: string
          description: "\n"
          format: string
        portalSettings:
          $ref: '#/components/schemas/PortalSettings'
        preferredLanguage:
          type: string
          description: "\n"
          format: string
        state:
          type: string
          description: "\n"
          format: string
    ClientResponse:
      type: object
      properties:
        _Example_Custom_Fields:
          type: object
          properties:
            Example_Checkbox_Field:
              type: string
              description: "\n"
              format: string
            Example_ClientLink_Field:
              type: string
              description: "\n"
              format: string
            Example_Date_Field:
              type: string
              description: "\n"
              format: string
            Example_Datetime_Field:
              type: string
              description: "\n"
              format: string
            Example_Free_Text_Field:
              type: string
              description: "\n"
              format: string
            Example_GroupLink_Field:
              type: string
              description: "\n"
              format: string
            Example_Number_Field:
              type: string
              description: "\n"
              format: string
            Example_Select_Field:
                $ref: '#/components/schemas/ExampleSelectFieldOption'
            Example_UserLink_Field:
              type: string
              description: "\n"
              format: string
        _Example_Grouped_CF_Set:
          type: array
          items:
            $ref: '#/components/schemas/ExampleGroupedCFSet'
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
        assignedBranchKey:
          type: string
          description: "\n"
          format: string
        assignedCentreKey:
          type: string
          description: "\n"
          format: string
        assignedUserKey:
          type: string
          description: "\n"
          format: string
        birthDate:
          type: string
          description: "\n"
          format: string
        clientRoleKey:
          type: string
          description: "\n"
          format: string
        emailAddress:
          type: string
          description: "\n"
          format: string
        firstName:
          type: string
          description: "\n"
          format: string
        gender:
          type: string
          description: "\n"
          format: string
        groupKeys:
          type: array
          items:
            type: string
        homePhone:
          type: string
          description: "\n"
          format: string
        id:
          type: string
          description: "\n"
          format: string
        idDocuments:
          type: array
          items:
            $ref: '#/components/schemas/IdDocument'
        lastName:
          type: string
          description: "\n"
          format: string
        middleName:
          type: string
          description: "\n"
          format: string
        mobilePhone:
          type: string
          description: "\n"
          format: string
        mobilePhone2:
          type: string
          description: "\n"
          format: string
        notes:
          type: string
          description: "\n"
          format: string
        portalSettings:
          $ref: '#/components/schemas/PortalSettings'
        preferredLanguage:
          type: string
          description: "\n"
          format: string
        state:
          type: string
          description: "\n"
          format: string
    InitiateClientRequest:
          $ref: '#/components/schemas/ClientRequest'
    InitiateClientResponse:
          $ref: '#/components/schemas/ClientResponse'
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: "\n"
          format: string
        status:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
  requestBodies:
    InitiateClientRequest:
        description: Initiate New Party
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/InitiateClientRequest'
  responses:
    InitiateClientResponse:
        description: PartyFacility 
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/InitiateClientResponse'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
