openapi: 3.0.1
info:
  title: Customer
  description: FinX BIAN service for Customer details.
  version: v9.156.4
servers:
- url: 'https://api-qa.fincuro.com/teller'
paths:
  '/clients:search':
    post:
      tags:
        - CustomerDetails
      summary: Retrieve details of customer
      description: Retrieve details of customers
      operationId: InitiateCustomersearch
      parameters:
        - $ref: '#/components/parameters/DetailsLevel'
      requestBody:
        $ref: '#/components/requestBodies/InitiateCustomerSearchRequest'
      responses:
        '200':
          $ref: '#/components/responses/InitiateCustomerSearchResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    SortingCriteria:
      type: object
      properties:
        field:
            type: string
            description: "\n"
            format: string
        order:
            type: string
            description: "\n"
            format: string
            enum:
              - ASC
              - DESC
    FilterCriteria:
      type: array
      items:
        type: object
        properties:
          field:
              type: string
              description: "\n"
              format: string
          value:
              type: string
              description: "\n"
              format: string
          operator:
              type: string
              description: "\n"
              format: string
              enum:
                - EQUALS
                - NOT_EQUALS
                - GREATER_THAN
                - LESS_THAN
          values:
              type: string
              description: "\n"
              format: string
              enum:
                - 'null'
    InitiateCustomerSearchRequest:
      type: object
      properties:
        sortingCriteria:
          $ref: '#/components/schemas/SortingCriteria'
        filterCriteria:
          $ref: '#/components/schemas/FilterCriteria'
    InitiateCustomerSearchResponse:
      type: array
      items:
        type: object
        properties:
          ActivationDate:
            type: string
            description: "\n"
            format: string
          ApprovedDate:
            type: string
            description: "\n"
            format: string
          AssignedBranchKey:
            type: string
            description: "\n"
            format: string
          AssignedCenterKey:
            type: string
            description: "\n"
            format: string
          BirthDate:
            type: string
            description: "\n"
            format: string
          ClientRoleKey:
            type: string
            description: "\n"
            format: string
          CreationDate:
            type: string
            description: "\n"
            format: string
          EmailAddress:
            type: string
            description: "\n"
            format: string
          EncodedKey:
            type: string
            description: "\n"
            format: string
          FirstName:
            type: string
            description: "\n"
            format: string
          LastName:
            type: string
            description: "\n"
            format: string
          Gender:
            type: string
            description: "\n"
            format: string
          groupLoanCycle:
            type: string
            description: "\n"
            format: string
          Id:
            type: string
            description: "\n"
            format: string
          LastModifiedDate:
            type: string
            description: "\n"
            format: string
          loanCycle:
            type: string
            description: "\n"
            format: string
          MobilePhone:
            type: string
            description: "\n"
            format: string
          State:
            type: string
            description: "\n"
            format: string
          PreferredLanguage:
            type: string
            description: "\n"
            format: string
          ProfilePictureKey:
            type: string
            description: "\n"
            format: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: "\n"
          format: string
        status:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
  parameters:
    DetailsLevel:
      name: details_level
      in: query
      required: true
      schema:
        type: string
  requestBodies:
    InitiateCustomerSearchRequest:
        description: fetchAccountUser
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/InitiateCustomerSearchRequest'
  responses:
    InitiateCustomerSearchResponse:
        description: fetchAccountUser
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/InitiateCustomerSearchResponse'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
