openapi: 3.0.1
info:
  title: Checking Account
  description: This service domain orchestrates a consumer checking account. The typical range of services and fees covers payments from and scheduled and ad-hoc deposits to the account, standing orders, sweeps, and liens.
  version: 12.0.1
servers:
- url: 'https://virtserver.swaggerhub.com/BIAN-3/BIAN/CurrentAccount/11.0.0'
paths:
   '/CheckingAccount/{checkingaccountid}/Deposits/Initiate':
    post:
      tags:
        - BQ - DepositsandWithdrawals
      summary: InBQ Initialize deposit transaction
      description: InBQ Initialize deposit transaction
      operationId: InitiateDepositsTransaction
      parameters:
        - $ref: '#/components/parameters/checkingaccountid'
      requestBody:
        $ref: '#/components/requestBodies/InitiatewithdrawalRequest'
      responses:
        '200':
          $ref: '#/components/responses/retrieveBalanceResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
   '/CheckingAccount/{checkingaccountid}/withdrawals/Initiate':
    post:
      tags:
        - BQ - DepositsandWithdrawals
      summary: InBQ Initialize withdrawal transaction
      description: InBQ Initialize withdrawal transaction
      operationId: Initiatewithdrwals
      parameters:
        - $ref: '#/components/parameters/checkingaccountid'
      requestBody:
        $ref: '#/components/requestBodies/InitiateDepositRequest'
      responses:
        '200':
          $ref: '#/components/responses/retrieveBalanceResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
   '/CheckingAccount/{checkingaccountid}/transactions/Retrieve':
    get:
      tags:
        - BQ - DepositsandWithdrawals
      summary: ReBQ Retrieve details about all transactions
      description: ReBQ Retrieve details about all transactions
      operationId: RetrieveAllTransactions
      parameters:
        - $ref: '#/components/parameters/checkingaccountid'
      responses:
        '200':
          $ref: '#/components/responses/Transactionsmessage'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    CheckingAccountFacility:
          type: object
          properties:
            ProductInstanceReference:
              type: string
              description: "\n"
              format: string
            CheckingAccountNumber:
              type: integer
              description: "\n"
              format: string
            CustomerReference:
              type: string
              description: "\n"
              format: string
            BankBranchLocationReference:
              type: string
              description: "\n"
              format: string
            AccountType:
              type: string
              description: "\n"
              format: string
            AccountCurrency:
              type: string
              description: "\n"
              format: string
            EntitlementOptionSetting:
              type: string
              description: "\n"
              format: string
            RestrictionOptionSetting:
              type: string
              description: "\n"
              format: string
            PositionLimitType:
              type: string
              description: "\n"
              format: string
            TransactionDateType:
              type: string
              description: "\n"
              format: string
    DepositsandWithdrawals:
          type: object
          properties:
            TransactionType:
              type: string
              description: "\n"
              format: string
            TransactionAmount:
              type: string
              description: "\n"
              format: string
            TransactionDescription:
              type: string
              description: "\n"
              format: string
            AccountLimitBreachResponse: 
              type: string
              description: "\n"
              format: string
    CheckingAccountFacilityResponse:
          type: object
          properties:
            TransactionReference:
              type: string
              description: "\n"
              format: string
            PositionLimitValue:
              type: string
              description: "\n"
              format: string
            DateType:
              type: string
              description: "\n"
              format: string
    Transactions:
        items:
          type: object
          properties:
            TransactionReference:
              type: string
              description: "\n"
              format: string
            TransactionType:
              type: string
              description: "\n"
              format: string
            AccountLimitBreachResponse:
              type: string
              description: "\n"
              format: string
            TransactionDescription:
              type: string
              description: "\n"
              format: string
            TransactionAmount:
              type: string
              description: "\n"
              format: string
            TransactionDate:
              type: string
              description: "\n"
              format: string
    CheckingAccountFacilitymessage:
      type: object
      properties:
        CheckingAccountFacility:
            $ref: '#/components/schemas/CheckingAccountFacility'
        DepositsandWithdrawals:
            $ref: '#/components/schemas/DepositsandWithdrawals'
    DepositsandWithdrawalsmessage:
      type: object
      properties:
        CheckingAccountFacility:
            $ref: '#/components/schemas/CheckingAccountFacility'
        DepositsandWithdrawals:
            $ref: '#/components/schemas/DepositsandWithdrawals'
    CheckingAccountFacilityResponsemessage:
      type: object
      properties:
        CheckingAccountFacilitymessage:
            $ref: '#/components/schemas/CheckingAccountFacilityResponse'
    Transactionsmessage:
      type: object
      properties:
        Transactions:
          $ref: '#/components/schemas/Transactions'
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: "\n"
          format: string
        status:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
  parameters:
    checkingaccountid:
      name: checkingaccountid
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBodies:
    InitiatewithdrawalRequest:
      description: Initiate withdrawal funds
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CheckingAccountFacilitymessage'
    InitiateDepositRequest:
      description: InitiateDeposit
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DepositsandWithdrawalsmessage'
  responses:
    retrieveBalanceResponse:
        description: fetchBalance
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/CheckingAccountFacilityResponsemessage'
    Transactionsmessage:
        description: fetchBalance
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/Transactionsmessage'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
