openapi: 3.0.1
info:
  title: Party
  description: BIAN Service Domain Packaged Business Capability (PCB) | DDD Bounded Context Party
  version: 11.0.0
servers:
- url: 'https://app.swaggerhub.com/apis/BIAN-3/CurrentAccount/11.0.0#/servers'
paths:
   /Party/Initiate:
    post:
      tags:
          - Party
      summary: InCR Initiate A new party
      description: InCR Initiate A party
      operationId: Initiate
      requestBody:
        $ref: '#/components/requestBodies/InitiatePartyRequest'
      responses:
        '200':
          $ref: '#/components/responses/InitiatePartyResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
   /Party/Retrieve:
    get:
      tags:
          - Party
      summary: ReCR Retrieve list of customers
      description: ReCR Retrieve list of customers
      operationId: RetrieveAll
      parameters:
        - $ref: '#/components/parameters/Status'
        - $ref: '#/components/parameters/PhoneIdentifiers'
        - $ref: '#/components/parameters/EmailIdentifiers'
        - $ref: '#/components/parameters/UsernameIdentifiers'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/PageToken'
      responses:
        '200':
          $ref: '#/components/responses/RetrievePartiesResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
   /Parties/{PartyReference}/Retrieve:
    get:
      tags:
          - Party
      summary: ReCR Retrieve details of party
      description: ReCR Retrieve details of party
      operationId: RetrieveParty
      parameters:
        - $ref: '#/components/parameters/PartyReference'
      responses:
        '200':
          $ref: '#/components/responses/RetrievePartyResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
   /Parties/{PartyReference}/Update:
    put:
      tags:
          - Party
      summary: UpCR Update details of a Party
      description: UpCR Update details of a Party
      operationId:  UpdateParty
      parameters:
        - $ref: '#/components/parameters/PartyReference'
      requestBody:
        $ref: '#/components/requestBodies/UpdatePartyRequest'
      responses:
        '200':
          $ref: '#/components/responses/UpdatePartyResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
   /Party-Addresses/Initiate:
    post:
      tags:
          - Party Address
      summary: InCR Initiate A new party
      description: InCR Initiate A party
      operationId: InitiatePartyAddress
      requestBody:
        $ref: '#/components/requestBodies/InitiatePartyAddressRequest'
      responses:
        '200':
          $ref: '#/components/responses/InitiatePartyAddressResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
   /Party-Addresses/{PartyAddressReference}/Update:
    put:
      tags:
          - Party Address
      summary: UpCR Update details of a Party Address
      description: UpCR Update details of a Party Address
      operationId: UpdatePartyAddress
      parameters:
        - $ref: '#/components/parameters/PartyAddressReference'
      requestBody:
        $ref: '#/components/requestBodies/UpdatePartyAddressRequest'
      responses:
        '200':
          $ref: '#/components/responses/UpdatePartyAddressResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    PartyName:
                  type: object
                  properties:
                    FirstName:
                      type: string
                      description: "\n"
                      format: string
                    MiddleName:
                      type: string
                      description: "\n"
                      format: string
                    LastName:
                      type: string
                      description: "\n"
                      format: string
    ElectronicAddressType:
                  type: object
                  properties:
                    ElectronicAddressTypeValue:
                      type: string
                      description: "\n"
                      format: string
                      enum:
                        - EmailAddress
                    AddressDescription:
                      type: string
                      description: "\n"
                      format: string
    MobilePhoneAddressType:
                    type: object
                    properties:
                      PhoneTypeValue:
                        type: string
                        description: "\n"
                        format: string
                        enum:
                          - MobileNumber
                      PhoneNumber:
                        type: string
                        description: "\n"
                        format: string
    HomePhoneAddressType:
                    type: object
                    properties:
                      PhoneTypeValue:
                        type: string
                        description: "\n"
                        format: string
                        enum:
                          - HomeNumber
                      PhoneNumber:
                        type: string
                        description: "\n"
                        format: string
    PartyReference:
              type: object
              properties:
                PartyName:
                  $ref: '#/components/schemas/PartyName'
                Title:
                  type: string
                  description: "\n"
                  format: string
                BirthDate:
                  type: string
                  description: "\n"
                  format: string
                Gender:
                  type: string
                  description: "\n"
                  format: string
                Nationality:
                  type: string
                  description: "\n"
                  format: string
                Residence:
                  type: string
                  description: "\n"
                  format: string
                TaxCountry:
                  type: string
                  description: "\n"
                  format: string
                ElectronicAddressType:
                  $ref: '#/components/schemas/ElectronicAddressType'
                MobilePhoneAddressType:
                  $ref: '#/components/schemas/MobilePhoneAddressType'
                HomePhoneAddressType:
                  $ref: '#/components/schemas/HomePhoneAddressType'
                PartyLegalStructureType: 
                  type: string
                  description: "\n"
                  format: string  
                  enum: 
                    - Person
                PartyInvolvementType:
                  type: string
                  description: "\n"
                  format: string
                  enum:
                    - AgreementInvolvement
    PartyReferrence:
              type: object
              properties:
                PartyReference:
                  type: string
                  description: "\n"
                  format: string
                Status:
                  type: string
                  description: "\n"
                  format: string
                PartyName:
                  $ref: '#/components/schemas/PartyName'
                Title:
                  type: string
                  description: "\n"
                  format: string
                BirthDate:
                  type: string
                  description: "\n"
                  format: string
                Gender:
                  type: string
                  description: "\n"
                  format: string
                Nationality:
                  type: string
                  description: "\n"
                  format: string
                Residence:
                  type: string
                  description: "\n"
                  format: string
                TaxCountry:
                  type: string
                  description: "\n"
                  format: string
                ElectronicAddressType:
                  $ref: '#/components/schemas/ElectronicAddressType'
                MobilePhoneAddressType:
                  $ref: '#/components/schemas/MobilePhoneAddressType'
                HomePhoneAddressType:
                  $ref: '#/components/schemas/HomePhoneAddressType'
                PartyLegalStructureType: 
                  type: string
                  description: "\n"
                  format: string  
                  enum: 
                    - Person
                PartyInvolvementType:
                  type: string
                  description: "\n"
                  format: string
                  enum:
                    - AgreementInvolvement
    PartyAddress:
      type: object
      properties:
        BuildingName:
                  type: string
                  description: "\n"
                  format: string
        StreetBuildingIdentification:
                  type: string
                  description: "\n"
                  format: string
        StreetName:
                  type: string
                  description: "\n"
                  format: string
        Municipality:
                  type: string
                  description: "\n"
                  format: string
        TownName:
                  type: string
                  description: "\n"
                  format: string
        PostCodeIdentification:
                  type: string
                  description: "\n"
                  format: string
        District:
                  type: string
                  description: "\n"
                  format: string
        Country:
                  type: string
                  description: "\n"
                  format: string
        AddressType:
                  type: string
                  description: "\n"
                  format: string
        FromDateTime:
                  type: string
                  description: "\n"
                  format: string
        ToDateTime:
                  type: string
                  description: "\n"
                  format: string
        PartyReference:
                  type: string
                  description: "\n"
                  format: string
    Party:
          type: object
          properties:
            PartyReference:
              $ref: '#/components/schemas/PartyReference'
    PartyResponse:
          type: object
          properties:
            PartyReference:
              $ref: '#/components/schemas/PartyReferrence'
    Parties:
      type: array
      items:
        type: object
        properties:
            PartyReference:
              $ref: '#/components/schemas/PartyReferrence'
    InitiatePartyRequest:
      type: object
      properties:
        Party: 
          $ref: '#/components/schemas/Party'
    InitiatePartyResponse:
      type: object
      properties:
        Party: 
          $ref: '#/components/schemas/PartyResponse'
    InitiatePartyAddressRequest:
      type: object
      properties:
        PartyAddress: 
          $ref: '#/components/schemas/PartyAddress'
    InitiatePartyAddressResponse:
      type: object
      properties:
        PartyAddressReference:
          type: string
          description: "\n"
          format: string
        PartyAddress: 
          $ref: '#/components/schemas/PartyAddress'
    UpdatePartyAddressRequest:
      type: object
      properties:
        PartyAddress: 
          $ref: '#/components/schemas/PartyAddress'
    UpdatePartyAddressResponse:
      type: object
      properties:
        PartyAddressReference:
          type: string
          description: "\n"
          format: string
        PartyAddress: 
          $ref: '#/components/schemas/PartyAddress'
    UpdatePartyRequest:
      type: object
      properties:
        Party: 
          $ref: '#/components/schemas/Party'
    UpdatePartyResponse:
      type: object
      properties:
        Party: 
          $ref: '#/components/schemas/PartyResponse'
    RetrievePartiesResponse:
      type: object
      properties:
        Parties: 
          $ref: '#/components/schemas/Parties'
    RetrievePartyResponse:
      type: object
      properties:
        Party:
          $ref: '#/components/schemas/PartyReferrence'
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: "\n"
          format: string
        status:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
  parameters:
    Status:
      name: Status
      in: query
      required: true
      schema:
        type: string
    PhoneIdentifiers:
      name: phone_identifier
      in: query
      required: false
      schema:
        type: string
    EmailIdentifiers:
      name: email_identifiers
      in: query
      required: false
      schema:
        type: string
    UsernameIdentifiers:
      name: username_identifiers
      in: query
      required: false
      schema:
        type: string
    PageSize:
      name: page_size
      in: query
      required: false
      schema:
        type: string
    PageToken:
      name: page_token
      in: query
      required: false
      schema:
        type: string
    PartyReference:
      name: PartyReference
      in: path
      required: true
      schema:
        type: string
    PartyAddressReference:
      name: PartyAddressReference
      in: path
      required: true
      schema:
        type: string
  requestBodies:
    InitiatePartyRequest:
      description: PartyInitiate
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiatePartyRequest'
    UpdatePartyRequest:
      description: PartyUpdate
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdatePartyRequest'
    UpdatePartyAddressRequest:
      description: PartyUpdate
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdatePartyAddressRequest'
    InitiatePartyAddressRequest:
        description: fetchParty
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/InitiatePartyAddressRequest'
  responses:
    InitiatePartyResponse:
        description: fetchParty
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/InitiatePartyResponse'
    InitiatePartyAddressResponse:
        description: fetchParty
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/InitiatePartyAddressResponse'
    UpdatePartyResponse:
        description: fetchParty
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/UpdatePartyResponse'
    UpdatePartyAddressResponse:
        description: fetchParty
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/UpdatePartyAddressResponse'
    RetrievePartiesResponse:
        description: fetchParties
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/RetrievePartiesResponse'
    RetrievePartyResponse:
        description: fetchParty
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/RetrievePartyResponse'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
