openapi: 3.0.1
info:
  title: Freeze Relationship service
  description: 'Freeze Relationship service.'
  version: 11.0.0
servers:
  - url: 'https://finx-celta-api-dev.fincuro.in'
paths:
  '/v1/fetchUserList':
    post:
      tags:
        - FinxFreezeRelationShipService
      summary: FinxFreezeRelationShipService
      description: FinxFreezeRelationShipService
      operationId: FinxFreezeRelationShipService
      requestBody:
        $ref: '#/components/requestBodies/InitiateRestrictionDefinitionRequest'
      responses:
        '200':
          $ref: '#/components/responses/InitiateRestrictionDefinitionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/v1/fetchUserListBasedOnName':
    post:
      tags:
        - FinxFreezeRelationShipService
      summary: FinxFreezeRelationShipService
      description: FinxFreezeRelationShipService
      operationId: ApplyRestriction
      requestBody:
         $ref: '#/components/requestBodies/InitiateApplyRestrictionRequest'
      responses:
        '200':
          $ref: '#/components/responses/InitiateApplyRestrictionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/v1/updateFreeze':
    post:
      tags:
        - FinxFreezeRelationShipService
      summary: FinxFreezeRelationShipService
      description: FinxFreezeRelationShipService
      operationId: UpdateRestriction
      requestBody:
         $ref: '#/components/requestBodies/InitiateUpdateRestrictionRequest'
      responses:
        '200':
          $ref: '#/components/responses/InitiateUpdateRestrictionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/v1/listOfRestrictionDefinition':
    get:
      tags:
        - FinxFreezeRelationShipService
      summary: FinxFreezeRelationShipService
      description: FinxFreezeRelationShipService
      operationId: listOfRestrictionDefinition
      parameters:
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveListofRestrictionDefinitionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/v1/listOfRestrictionDefinitionVersion':
    get:
      tags:
        - FinxFreezeRelationShipService
      summary: FinxFreezeRelationShipService
      description: FinxFreezeRelationShipService
      operationId: listOfRestrictionDefinitionVersion
      parameters:
        - $ref: '#/components/parameters/excludePreviousVersions'
        - $ref: '#/components/parameters/restrictionSetDefinitionId'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveListofRestrictionDefinitionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/v1/listRestrictionsBasedOnId':
    get:
      tags:
        - FinxFreezeRelationShipService
      summary: FinxFreezeRelationShipService
      description: FinxFreezeRelationShipService
      operationId: listRestrictionsBasedOnId
      parameters:
        - $ref: '#/components/parameters/accountId'
        - $ref: '#/components/parameters/customerId'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveListRestrictionsBasedOnIdResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'        
components:
  schemas:
    InitiateRestrictionDefinitionResponse:
      type: object
      properties:
        id:
          type: string
        restrictionDefinion:
          $ref: '#/components/schemas/restrictionDefinion'
        restrictionSetDefinitionId:
          type: string
          format: string
          description: "/n" 
        description:
          type: string
          format: string
          description: "/n" 
        requestId:
          type: string
          format: string
          description: "/n"  
    restrictionDefinion:
      type: array
      items:
        type: object
        properties: 
          restrictionType:
            type: string
          requiredRestrictionLevels:
            $ref: '#/components/schemas/requiredRestrictionLevels'
    requiredRestrictionLevels:
      type: array
      items:
        type: string
    InitiateApplyRestrictionResponse:
      type: object
      properties:
        id:
          type: string
          format: string
          description: "\n"
        restrictionSetDefinitionId:
          type: string
          format: string
          description: "\n"
        restrictionSetDefinitionVersionId:
          type: string
          format: string
          description: "\n"
        name:
          type: string
          format: string
          description: "\n"
        restrictions:  
          $ref: '#/components/schemas/restrictions'  
        description:
          type: string
          format: string
          description: "\n"
        restrictionSetParameters:
          type: string
          format: string
          description: "\n"
        customerId:
          type: string
          format: string
          description: "\n"
        accountId:
          type: string
          format: string
          description: "\n"
        paymentDeviceId:
          type: string
          format: string
          description: "\n"
        effectiveTimestamp:
          type: string
          format: string
          description: "\n"
        expiryTimestamp:
          type: string
          format: string
          description: "\n"
        isActive:
          type: string
          format: string
          description: "\n"  
    restrictions:
          type: array
          items:
            type: object
            properties:
              restrictionType:
                type: string
                format: string
                description: "\n"
              accountId:
                type: string
                format: string
                description: "\n"
              paymentDeviceId:
                type: string
                format: string
                description: "\n"
              effectiveTimestamp:
                type: string
                format: string
                description: "\n"
              expiryTimestamp:
                type: string
                format: string
                description: "\n"
              id:
                type: string
                format: string
                description: "\n"  
    InitiateApplyRestrictionRequest:      
      type: object
      properties:
        restrictionType:
          type: string
          format: string 
        name:
          type: string
          format: string 
        restrictionDefinitionID:
          $ref: '#/components/schemas/restrictionDefinitionID'  
        description:
          type: string
          format: string 
        requestId:
          type: string
          format: string 
        corporateId:
          type: string
          format: string   
    restrictionDefinitionID:
      type: array
      items:
        type: string
    InitiateRestrictionDefinitionRequest:
      type: object
      properties:
        restrictionType:
          type: string
          format: string
        restrictionDefinion:  
          $ref: '#/components/schemas/restrictionDefinionRequest'  
        restrictionDefinitionID:
          type: string
          format: string
        description:
          type: string
          format: string
        requestId:
          type: string
          format: string
    restrictionDefinionRequest:
      type: array
      items:
        type: string
    InitiateUpdateRestrictionRequest:
      type: object
      properties:
        applyRestrictionID:
          type: string
          format: string
        isActive :
          type: string
          format: string
        requestId:
          type: string
          format: string 
    InitiateUpdateRestrictionResponse:
      type: object
      properties:
        id:
          type: string
          format: string
        restrictionSetDefinitionId:
          type: string
          format: string
        restrictionSetDefinitionVersionId:
          type: string
          format: string
        name:
          type: string
          format: string
        restrictions:
          $ref: '#/components/schemas/restrictionsUpdate'
        description:
          type: string
          format: string
        restrictionSetParameters:
          $ref: '#/components/schemas/restrictionSetParameters'  
        customerId:
          type: string
          format: string
        accountId:
          type: string
          format: string
        paymentDeviceId:
          type: string
          format: string
        effectiveTimestamp:
          type: string
          format: string
        expiryTimestamp:
          type: string
          format: string 
        isActive:
          type: string
          format: string
    restrictionsUpdate:
      type: array
      items:
        type: object
        properties:
          restrictionType:
            type: string
            description: "\n"
            format: string
          parameters:
            $ref: '#/components/schemas/restrictParameters'  
          customerId:
            type: string
            description: "\n"
            format: string
          accountId:
            type: string
            description: "\n"
            format: string
          paymentDeviceId:
            type: string
            description: "\n"
            format: string
          effectiveTimestamp:
            type: string
            description: "\n"
            format: string 
          expiryTimestamp:
            type: string
            description: "\n"
            format: string 
          id:
            type: string
            description: "\n"
            format: string 
    restrictionSetParameters:
      type: object
      additionalProperties: false
    restrictParameters:
      type: object
      additionalProperties: false  
    restrictionSetDefinitions:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: "\n"
                format: string 
              name:
                type: string
                description: "\n"
                format: string 
              isActive:
                type: string
                description: "\n"
                format: string 
    RetrieveListofRestrictionDefinitionResponse:
      type: object
      properties:
        restrictionSetDefinitions:
          $ref: '#/components/schemas/restrictionSetDefinitions'
        previousPageToken: 
          type: string
          description: "\n"
          format: string
        nextPageToken: 
          type: string
          description: "\n"
          format: string
    RetrieveListRestrictionsBasedOnIdResponse:
      type: object
      properties:
        restrictions:
          $ref: '#/components/schemas/restrictionsDetails' 
    restrictionsDetails:
      type: array
      items:
        type: object
        properties:
          restrictionType:
            type: string
            description: "\n"
            format: string 
          parametersDetails:
            $ref: '#/components/schemas/parametersDetails'
          customerId: 
            type: string
            description: "\n"
            format: string
          accountId: 
            type: string
            description: "\n"
            format: string
          paymentDeviceId: 
            type: string
            description: "\n"
            format: string
          effectiveTimestamp: 
            type: string
            description: "\n"
            format: string
          expiryTimestamp: 
            type: string
            description: "\n"
            format: string
          id: 
            type: string
            description: "\n"
            format: string   
    parametersDetails:
      type: object
      properties:
        preventDebitsExemptionConditions:
          type: object
          properties:
            eventName:
              type: string
    HTTPError:
      type: object
      properties:
        statusCode:
          type: string
          description: "\n"
          format: string
        status:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
  requestBodies:
    InitiateApplyRestrictionRequest:
      description: InitiateApplyRestrictionRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateApplyRestrictionRequest'
    InitiateRestrictionDefinitionRequest:
      description: InitiateRestrictionDefinitionRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateRestrictionDefinitionRequest'
    InitiateUpdateRestrictionRequest:
      description: InitiateUpdateRestrictionRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateUpdateRestrictionRequest'        
  responses:
    InitiateRestrictionDefinitionResponse:
      description: InitiateRestrictionDefinitionResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateRestrictionDefinitionResponse'
    InitiateApplyRestrictionResponse:
      description: InitiateApplyRestrictionResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateApplyRestrictionResponse' 
    InitiateUpdateRestrictionResponse:
      description: InitiateUpdateRestrictionResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateUpdateRestrictionResponse'
    RetrieveListofRestrictionDefinitionResponse:
      description: RetrieveListofRestrictionDefinitionResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveListofRestrictionDefinitionResponse'
    RetrieveListRestrictionsBasedOnIdResponse: 
      description: RetrieveListRestrictionsBasedOnIdResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveListRestrictionsBasedOnIdResponse'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
  parameters:
    pageSize:    
      name: pageSize
      in: query
      required: true
      schema:
        type: string
    excludePreviousVersions:    
      name: excludePreviousVersions
      in: query
      required: false
      schema:
        type: string
    restrictionSetDefinitionId:    
      name: restrictionSetDefinitionId
      in: query
      required: false
      schema:
        type: string
    accountId:    
      name: accountId
      in: query
      required: false
      schema:
        type: string
    customerId:    
      name: customerId
      in: query
      required: false
      schema:
        type: string    