openapi: 3.0.0
info:
  title: Open Banking
  description: This specification covers the APIs for the Equifax Open Banking Insights Product. .
  version: 1.2.32
servers:
- url: "https://api.sandbox.equifax.co.uk/open-banking-insights/v1"
x-comments: 
  -CONSUMER:"These APIs are available to clients that register for the consumer product.""
paths:
   /commercial/businessHealthCharacteristics:
    get:
      tags:
          - SavingsAccountFacility
      summary: InCR Initiate A new savings account
      description: InCR Initiate A new savings account
      operationId: Initiate
      parameters:
      - $ref: "#/components/parameters/CustomerIdParam"
      responses:
        '200':
          $ref: '#/components/responses/RetrieveFhiScoreResponseResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    Flags:
      type: object
      properties:
        flag:
          type: string
          description: The flag associated with the score
        description:
          type: string
          description: Description of the flag
        level:
          type: string
          description: Level of the flag
    FhiScoreResponse:
      type: object
      properties:
        fhiScore:
          type: integer
          description: The FHI (Flagged Health Indicator) score
        flags:
          type: array
          description: List of flags associated with the score
          items:
            $ref: '#/components/schemas/Flags'
    InitiateFhiScoreResponseResponse:
          $ref: '#/components/schemas/FhiScoreResponse'
    HTTPError:
      type: object
      properties:
        log_ref:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
  parameters:
    CustomerIdParam:
      name: customerId
      in: query
      description: "Internal Id of the customer. This can be retrieved from the general/lookup/customerId endpoint when providing an external client reference."
      required: true
      schema:
        type: string
  headers:
    EfxClientCorrelationIdParam:
      description: "This is a client reference ID, which is returned in the response.This can be used by clients for their own reference and logging purposes."
      schema:
        type: "string"
  responses:
    RetrieveFhiScoreResponseResponse:
      description: fetchFhiScoreResponse
      headers:
        EfxClientCorrelationIdParam:
          $ref: '#/components/headers/EfxClientCorrelationIdParam'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateFhiScoreResponseResponse'

    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'