openapi: 3.0.1
info:
  title: Open Banking
  description: This specification covers the APIs for the Equifax Open Banking Insights Product. .
  version: 1.2.32
servers:
- url: "https://api.sandbox.equifax.co.uk/open-banking-insights/v1"
paths:
   /commercial/businessHealthCharacteristics:
    get:
      tags:
          - CONSUMER
      description: Equifax Business Health Characteristics uses current account transaction data to offer you a more complete picture of a company's financial health,helping you make more accurate lending decisions. Because it uses transaction data, it doesn’t rely on your business customers having a history of credit,in order to determine their ability to pay back a loan, invoice finance or asset finance agreement.<p>This means that you can more accurately assess the creditworthiness and affordability of UK businesses who are applying to the CBILS scheme with characteristics that show turnover and payments such as Tax and Salary. Characteristics are available over 1,3,6, 12 and 24 months and cover pre-COVID (pre March 1 2020), post-COVID (post March 1 2020) and rolling periods (crossing the ‘COVID’ date) in addition to chars that cover loans and other borrowing taken during the COVID period.</p>"
      operationId: Retrieve
      parameters:
      - $ref: "#/components/parameters/CustomerIdParam"
      responses:
        '200':
          $ref: '#/components/responses/RetrieveFhiScoreResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    Flags:
      type: array
      items:
        type: object
        properties:
          flag:
            type: string
            description: "\n"
            format: string
          description:
            type: string
            description: "\n"
            format: string
          level:
            type: string
            description: "\n"
            format: string
    FhiScoreResponse:
      type: object
      properties:
        fhiScore:
          type: string
          description: "\n"
          format: string
        flags:
            $ref: '#/components/schemas/Flags'
    InitiateFhiScoreResponse:
          $ref: '#/components/schemas/FhiScoreResponse'
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: "\n"
          format: string
        status:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
  parameters:
    CustomerIdParam:
      name: customerId
      in: query
      required: true
      schema:
        type: string
  responses:
    RetrieveFhiScoreResponse:
      description: fetchFhiScore
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateFhiScoreResponse'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
