openapi: 3.0.1
info:
  title: Open Banking
  description: This specification covers the APIs for the Equifax Open Banking Insights Product. .
  version: 1.2.32
servers:
- url: "https://api.sandbox.equifax.co.uk/open-banking-insights/v1"
paths:
   /commercial/{CustomerIdParam}/businessHealthCharacteristics:
    get:
      tags:
          - CONSUMER
      summary: Business Health Characteristics Data
      description: Equifax Business Health Characteristics uses current 
      operationId: Retrieve
      parameters:
      - $ref: "#/components/parameters/CustomerIdParam"
      responses:
        '200':
          $ref: '#/components/responses/RetrieveFhiScoreResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    Flags:
      type: array
      items:
        type: object
        properties:
          flag:
            type: string
            description: "\n"
            format: string
          description:
            type: string
            description: "\n"
            format: string
          level:
            type: string
            description: "\n"
            format: string
    FhiScoreResponse:
      type: object
      properties:
        fhiScore:
          type: string
          description: "\n"
          format: string
        flags:
            $ref: '#/components/schemas/Flags'
    RetrieveFhiScoreResponse:
          $ref: '#/components/schemas/FhiScoreResponse'
    HTTPError:
      type: object
      properties:
        logref:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
  parameters:
    CustomerIdParam:
      name: customerId
      in: path
      required: true
      schema:
        type: string
  responses:
    RetrieveFhiScoreResponse:
      description: fetchFhiScore
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveFhiScoreResponse'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
