openapi: 3.0.1
info:
  title: Open Banking
  description: This specification covers the APIs for the Equifax Open Banking Insights Product. .
  version: 1.2.32
servers:
- url: "https://api.sandbox.equifax.co.uk/open-banking-insights/v1"
paths:
  /consumer/financialHealthIndex:
    get:
      tags:
          - CONSUMER
      summary: Financial Health Index (V1)
      description: "Financial Health Index is a single metric that summarises a customer’\
        s financial health based on current account transaction data. It uses open\
        \ banking technology to analyse a customer’s current account data in real\
        \ time and identify their likelihood of making credit repayments. The Index\
        \ (values 1- 9) ranks an individual's creditworthiness based on behaviours\
        \ and insights found in account information. Proven to be highly predictive\
        \ of credit risk, the FHI can be used in combination with traditional credit\
        \ scoring approaches to improve the assessment of creditworthiness by incorporating\
        \ insights from account information (income, salary, rental payments, council\
        \ tax payments, account surplus, etc.) for a more holistic risk assessment.\
        \ Transparent and explainable, alongside the FHI are supplied 26 credit risk\
        \ indicators that help explain why the individual has been assigned the index\
        \ value. Financial Health Index (V1) is based on amount of account information\
        \ requested, e.g. 3, 6 and 12 months of data." 
      operationId: RetrieveFHI
      parameters:
          - $ref: "#/components/parameters/CustomerIdParam"
          - $ref: "#/components/parameters/NumberOfMonths1361224Param"
          - $ref: "#/components/parameters/EfxClientCorrelationIdParam"
      responses:
        '200':
          $ref: '#/components/responses/RetrieveFinancialHealthIndexResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /consumer/financialHealthIndex/months:
    get:
      tags:
          - CONSUMER
      summary: Financial Health Index (V2)
      description: "Financial Health Index V2 is an improved version of the Financial\
        \ Health Index V1 where all data can be returned in the output, e.g. 3, 6\
        \ and 12 months of data." 
      operationId: RetrieveFHIM
      parameters:
          - $ref: "#/components/parameters/CustomerIdParam"
          - $ref: "#/components/parameters/NumberOfMonth1361224Param"
          - $ref: "#/components/parameters/EfxClientCorrelationIdParam"
      responses:
        '200':
          $ref: '#/components/responses/RetrieveFinancialHealthIndexMonthsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    flags:
      type: array
      items:
        type: object
        properties:
          flag:
            type: string
            description: "\n"
            format: string
          description:
            type: string
            description: "\n"
            format: string
          level:
            type: string
            description: "\n"
            format: string
    RetrieveFinancialHealthIndexResponse:
      type: object
      properties:
        fhiScore:
          type: string
          description: "\n"
          format: string
        flags:
          $ref: '#/components/schemas/flags'
    RetrieveFinancialHealthIndexMonthsResponse:
      type: object
      properties:
        numberOfMonths:
          type: string
          description: "\n"
          format: string
        fhiScore:
          type: string
          description: "\n"
          format: string
        flags:
          $ref: '#/components/schemas/flags'
    HTTPError:
      type: object
      properties:
        logref:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
  parameters:
    CustomerIdParam:
      name: customerId
      description: "Internal Id of the customer. This can be retrieved from the /general/lookup/customerId\
        \ endpoint when providing an external client reference."
      in: query
      required: true
      schema:
        type: string
    NumberOfMonths1361224Param:
      name: numberOfMonths
      description: "1, 3, 6, 12 or 24 months of transaction data to be utilised in\
        \ the response calculation."
      in: query
      required: true
      schema:
        type: string
    NumberOfMonth1361224Param:
      name: numberOfMonth
      description: "An array of integers, containing either 3, 6 or 12 months for\
        \ transaction data to be provided in the response."
      in: query
      schema:
        type: string
    EfxClientCorrelationIdParam:
      name: efx-client-correlation-id
      description: "This is a client reference ID, which is returned in the response.\
        \ This can be used by clients for their own reference and logging purposes."
      in: header
      schema:
        type: string
  responses:
    RetrieveFinancialHealthIndexResponse:
      description: fetchFhiScore
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveFinancialHealthIndexResponse'
    RetrieveFinancialHealthIndexMonthsResponse:
      description: fetchFhiScore
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveFinancialHealthIndexMonthsResponse'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'