openapi: 3.0.1
info:
  title: Transfer Funds
  description: 'This service domain orchestrates the transfer funds between an accounts.'
  version: 11.0.0
servers:
  - url: https://api-qa.fincuro.com
paths:
  '/fundtransfer':
    post:
      tags:
        - Transfer Funds
      summary: Initiate transfer funds between accounts.
      description: Initiate transfer funds between accounts.
      operationId: InitiateTransferFunds.
      requestBody:
          $ref: '#/components/requestBodies/InitiatetransferRequest'
      responses:
        '200':
          $ref: '#/components/responses/InitiatetransferResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    OccurrenceAmount:
      type: object
      properties:
            value:
              type: string
              description: "\n"
              format: string
            currencyCode:
              type: string
              description: "\n"
              format: string        
    TransferOccurrence:
      type: array
      items:
          type: object
          properties:
            occurrenceFromAccountId:
              type: string
              description: "\n"
              format: string
            occurrenceToAccountId:
              type: string
              description: "\n"
              format: string
            occurrenceFromCoreId:
              type: string
              description: "\n"
              format: string
            occurrenceToCoreId:
              type: string
              description: "\n"
              format: string
            concurrenceStatus:
              type: string
              description: "\n"
              format: string
            fundsWithdrawalType:
              type: string
              description: "\n"
              format: string
            occurrenceMemo:
              type: string
              description: "\n"
              format: string
            estimatedProcessDateTime:
              type: string
              description: "\n"
              format: string
            createdDateTime:
              type: string
              description: "\n"
              format: string
            queuedForPosting:
              type: string
              description: "\n"
              format: string
            note:
              type: string
              description: "\n"
              format: string
            batchId:
              type: string
              description: "\n"
              format: string
            occurrenceAmount:
              $ref: '#/components/schemas/OccurrenceAmount'
    InitiatetransferRequest:
      type: object
      properties:
        transferOccurrenceMessage:
          type: object
          properties:
            messageContext:
              type: string
              description: string
              format: string
            transferOccurenceList:
              type: object
              properties:
                transferOccurence:
                  $ref: '#/components/schemas/TransferOccurrence'
    InitiatetransferResponse:
      type: object
      properties:
        transferOccurrenceMessage:
          type: object
          properties:
            messageContext:
              type: string
              description: string
              format: string
            transferOccurenceList:
              type: object
              properties:
                transferOccurence:
                  $ref: '#/components/schemas/TransferOccurrence'
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: "\n"
          format: string
        status:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
  requestBodies:
    InitiatetransferRequest:
      description: Initiate transfer funds
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiatetransferRequest'
  responses:
    InitiatetransferResponse:
        description: Initiate transfer funds
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/InitiatetransferResponse'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'