openapi: 3.0.1
info:
  title: Payment posting test
  description: BIAN Service Domain Packaged Business Capability (PCB) | DDD Bounded Context Beneficiaries.
  version: 12.0.1
servers:
- url: 'https://core-api.shine.staging.saas.tmachine.io'
paths:
   /Payments/postings:
    post:
      tags:
          - Posting payments
      summary: Payments to be posted to an account.
      description: Payments to be posted to an account.
      operationId: Postingpayment
      requestBody:
          $ref: '#/components/requestBodies/Postingamount'
      responses:
        '200':
          $ref: '#/components/responses/Postingamount'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    Postingamount:
      type: object
      properties:
        postingId:
          type: string
          description: "\n"
          format: string
        clientTransactionId:
          type: string
          description: "\n"
          format: string
        status:
          type: string
          description: "\n"
          format: string
        postingViolations:
          $ref: '#/components/schemas/postingViolations'
        accountViolations:
          $ref: '#/components/schemas/accountViolations'
        restrictionViolations:
          $ref: '#/components/schemas/restrictionViolations'
        contractViolations:
          $ref: '#/components/schemas/contractViolations'
    postingViolations:
      type: array
      items:
        properties: 
          type:
           type: string
           description: "\n"
           format: string
    accountViolations:
      type: array
      items:
        properties: 
          accountId:
           type: string
           description: "\n"
           format: string
          paymentDeviceToken:
           type: string
           description: "\n"
           format: string
          type:
           type: string
           description: "\n"
           format: string
    restrictionViolations:
      type: array
      items:
        properties: 
          restrictionSetId:
           type: string
           description: "\n"
           format: string
          accountId:
           type: string
           description: "\n"
           format: string
          paymentDeviceId:
           type: string
           description: "\n"
           format: string
          customerId:
           type: string
           description: "\n"
           format: string
    contractViolations: 
      type: array
      items:
        properties: 
          accountId:
           type: string
           description: "\n"
           format: string
          type:
           type: string
           description: "\n"
           format: string
          reason:
           type: string
           description: "\n"
           format: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: "\n"
          format: string
        status:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
  requestBodies:
    Postingamount:
      description: Posting Amount
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Postingamount'
  responses:
    Postingamount:
        description: Posting Amount
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/Postingamount'
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'